import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { drupal } from "@/drupal/drupal";
import { DrupalMenuLinkContent } from "next-drupal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { tree: hamburgerMenu } = await drupal.getMenu<DrupalMenuLinkContent>(
    "hamburger",
    { locale: "es", defaultLocale: "es" }
  );

  return (
    <html lang="en">
      {JSON.stringify(hamburgerMenu)}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
